version: 0.2
proxy:
  upload-artifacts: yes
  logs: yes
env:
  shell: bash
  exported-variables:
    - EXPORT_VAR1
    - EXPORT_VAR2
phases:
  install:
    runtime-versions:
      php: 8.4.6
    commands:
      - curl -I https://www.php.net
      - nslookup www.php.net
      - traceroute www.php.net
      - export EXPORT_VAR1="value444444"
      - export EXPORT_VAR2="value555555"
  pre_build:
    on-failure: ABORT
    commands:
      - echo "pre-build"
  build:
    on-failure: ABORT
    commands:
      - echo "build"
    finally:
      - echo "finally"
  post_build:
    on-failure: ABORT
    commands:
      - echo "post-build"
